version: '3.9'

services:
  frontend:
    build: frontend/
    ports:
      - "5173:5173"
    networks:
      - "mtrack-network"
  backend:
    build: backend/
    ports:
      - "4000:4000"
    networks:
      - "mtrack-network"
    depends_on:
      - frontend
      - redis
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1  # Cloudflare DNS
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - "mtrack-network"

networks:
  mtrack-network:
    driver: bridge