apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mtrack
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}