apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mtrack
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}