apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mtrack
  labels:
    app: redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: redis
        ports:
        - containerPort: {{ .Values.service.port }}